version: '2'
services:
    mysql:
        image: mysql:5.6
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=forum
        ports:
            - 3306:3306
        volumes:
            - /home/lipengfei/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        restart: always
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
          - mysql
      links:
          - mysql
      environment:
          PMA_HOST: mysql
          PMA_USER: root
          PMA_PASSWORD: test
      ports:
          - 8081:80
      restart: always
    redis:
        image: redis
        container_name: my_redis
        command: redis-server --requirepass 123456
        volumes:
          - ./data:/data
        ports:
            - 6379:6379
        restart: always
